// <auto-generated />
namespace AdminLteMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createtablecro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtablecro));
        
        string IMigrationMetadata.Id
        {
            get { return "202104150347136_create table cro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
