// <auto-generated />
namespace AdminLteMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createtableforRequestDeliverySchedule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtableforRequestDeliverySchedule));
        
        string IMigrationMetadata.Id
        {
            get { return "202104140149429_create table for Request Delivery Schedule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
